1. NumPy - Creation of an array

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


2. Array Arithmetic

In [2]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Addition
c = a + b
print(c)

# Multiplication
d = a * b
print(d)

# Dot product
dot_product = np.dot(a, b)
print(dot_product)


[5 7 9]
[ 4 10 18]
32


3. Reshaping an Array

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape((2, 3))
print(reshaped_arr)


[[1 2 3]
 [4 5 6]]


4. Indexing & Slicing

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Accessing an element
print(arr[0])

# Slicing
print(arr[1:4])

# Boolean indexing
bool_idx = arr > 3
print(arr[bool_idx])


1
[2 3 4]
[4 5]


5. Mathematical Functions

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Square root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sum and mean
print(np.sum(arr))
print(np.mean(arr))


[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
15
3.0


6. Transposition of an Array

In [6]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

# Transpose
transposed_arr = arr.T
print(transposed_arr)


[[1 4]
 [2 5]
 [3 6]]


7. Concatenation of Arrays

In [7]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Concatenating along axis 0 (row-wise)
concatenated_arr = np.concatenate((a, b), axis=0)
print(concatenated_arr)


[1 2 3 4 5 6]


8. Broadcasting

In [9]:
import numpy as np

a = np.array([1, 2, 3])
b = 5

# Broadcasting scalar to array
result = a + b
print(result)


[6 7 8]


9. Statistical Functions

In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Minimum value
print(np.min(arr))

# Maximum value
print(np.max(arr))

# Mean
print(np.mean(arr))

# Standard deviation
print(np.std(arr))


1
5
3.0
1.4142135623730951


10. Linear Algebra Operations

In [10]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Matrix multiplication
result = np.matmul(a, b)
print(result)

# Determinant
determinant = np.linalg.det(a)
print(determinant)


[[19 22]
 [43 50]]
-2.0000000000000004
